### ISSUE TITLE
Minor comments on sf_load_save tutorial

### ISSUE THREAD

**Issue by florisvdh** [kadyb/sf_load_save#2]
Reads well, nice tutorial! :+1: 

Some minor suggestions:

- explicitly advise using relative filepaths as this will make R scripts portable. See also https://r4ds.hadley.nz/workflow-scripts#relative-and-absolute-paths
- I believe it's good practice to always run `st_layers()` on a GeoPackage first. You could do it to actually demonstrate there is indeed just one layer in the GeoPackage
- another I proposed in PR #1

**Comment by kadyb** [comment]
Thanks! I included your comments in the update.
